- name: Install nginx
  ansible.builtin.apt:
      name: nginx
      state: present

- name: Configure Nginx as a reverse proxy for uWSGI
  ansible.builtin.copy:
    src: default
    mode: '0644'
    dest: /etc/nginx/sites-enabled/default

  notify: 
    - restart nginx