- name: Install nginx
  ansible.builtin.apt:
      name:
      - nginx
      - prometheus-nginx-exporter
      state: present
  become: yes

- name: Template Nginx Config
  ansible.builtin.template:
      src: default.j2
      dest: /etc/nginx/sites-enabled/default
      mode: '0644'
  notify: 
    - Restart Nginx
  become: yes


- name: Enable and Start Nginx Service
  service:
    name: nginx
    state: started
    enabled: true
  become: yes

