- name: Install nginx
  ansible.builtin.apt:
      name:
      - nginx
      - prometheus-nginx-exporter
      state: present

- name: Template Nginx Config
  ansible.builtin.template:
      src: default.j2
      dest: /etc/nginx/sites-enabled/default
      mode: '0644'
  notify: 
    - Restart Nginx
    - Restart Nginx Exporter

- name: Ensure Nginx is running and enabled on startup
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Enable prometheus nginx exporter
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: started
    enabled: true

