---

# Install InfluxDB
- name: Download influxdb
  get_url:
   url: "https://dl.influxdata.com/influxdb/releases/influxdb_1.8.10_amd64.deb"
   dest: "/home/ubuntu/influxdb"

- name: Install influxdb
  apt:
   deb: "/home/ubuntu/influxdb"
   state: present

- name: Configure influxdb
  copy:
    src: influxdb.conf
    dest: /etc/influxdb/influxdb.conf
  notify: Restart influxdb

- name: Activate influxdb
  service:
    name: influxdb
    state: started
    enabled: true

