- name: Install uWSGI
  apt:
    name: uwsgi
    state: present

- name: Install Dependencies
  apt:
    name: uwsgi-plugin-python3
    state: present      

- name: Template uWSGI config
  template:
    src: ../files/agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: 0600
  no_log: true
  notify: restart uwsgi

- name: Enable and start uWSGI service
  service:
    name: uwsgi
    state: started
    enabled: true