- name: Install uWSGI
  apt:
    name: 
    - uwsgi
    - uwsgi-plugin-python3
    state: present

- name: Configure host uwsgi
  ansible.builtin.template:
    src:  agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: '0600'
  no_log: true
  notify: restart uwsgi

- name: Enable and start uWSGI service
  service:
    name: uwsgi
    state: started
    enabled: true