- name: Restart Bind9
  service:
    name: bind9
    state: restarted

- name: RNDC Reload
  ansible.builtin.command: rndc reload
  changed_when: true

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  