- name: Install Prometheus
  apt:
    name: prometheus
    state: present

- name: Copy Prometheus default file
  ansible.builtin.template:
    src: prometheus.j2
    dest: /etc/default/prometheus
  notify:
    - Restart Prometheus

- name: Add VMs to prometheus target
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify:
    - Restart Prometheus

- name: Enable Prometheus
  service:
    name: prometheus 
    state: started
    enabled: yes

