- name: Install Bind9
  apt:
    name: bind9
    state: present

- name: Template named.conf.options
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Restart Bind9

- name: Template named.conf.local
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: Restart Bind9

- name: Template forward zone file
  template:
    src: db.forward.j2
    dest: /var/cache/bind/db.{{ domain_name }}
  notify: Restart Bind9

- name: Template reverse zone file
  template:
    src: db.reverse.j2
    dest: /var/cache/bind/db.{{ reverse_domain_name }}
  notify: Restart Bind9

- name: Validate Bind9 Configuration
  command: named-checkconf
  register: checkconf
  changed_when: false
  failed_when: checkconf.rc != 0

- name: Validate Forward Zone
  command: named-checkzone {{ domain_name }} /var/cache/bind/db.{{ domain_name }}
  register: forward_zone_check
  changed_when: false
  failed_when: forward_zone_check.rc != 0

- name: Validate Reverse Zone
  command: named-checkzone {{ reverse_domain_name }} /var/cache/bind/db.{{ reverse_domain_name }}
  register: reverse_zone_check
  changed_when: false
  failed_when: reverse_zone_check.rc != 0


# Prometheus bind9 exporter
- name: Install unzip
  apt:
    name: unzip
    state: present

- name: Download Prometheus bind9 exporter to '/opt'
  unarchive:
    src: https://github.com/prometheus-community/bind_exporter/releases/download/v0.6.1/bind_exporter-0.6.1.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes

- name: Create symlink to bind_exporter executable
  file:
    src: /opt/bind_exporter-0.6.1.linux-amd64/bind_exporter
    dest: /usr/local/bin/prometheus-bind-exporter
    state: link

- name: Copy bind_exporter systemd service file
  template:
    src: prometheus_bind_exporter.service.j2
    dest: /etc/systemd/system/prometheus-bind-exporter.service
  notify:
    - Reload systemd

- name: Ensure Bind9 and Bind Exporter is running and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - bind9
    - prometheus-bind-exporter

