- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400
  
- name: Install Prometheus Node Exporter
  apt:
    name: prometheus-node-exporter
    state: present

- name: Ensure Prometheus Node Exporter is running
  systemd:
    name: prometheus-node-exporter
    state: started
    enabled: yes

#Backup User
- name: Create backup user
  user:
    name: backup
    home: /home/backup
    generate_ssh_key: true
    ssh_key_file: /home/backup/.ssh/id_rsa
    
- name: Add backup server to known hosts
  template:
    src: known_hosts
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup
    mode: 0600